import { Injectable } from '@nestjs/common';
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { AppConfigService, RuntimeTerrariaConfig } from '../config/config.service';

@Injectable()
export class ServerConfigService {
  constructor(private readonly configService: AppConfigService) {}

  getConfigPath(): string {
    return join(this.configService.getDataPath(), 'serverconfig.txt');
  }

  resolveWorldPath(config: RuntimeTerrariaConfig): string {
    if (config.worldPath) {
      return config.worldPath;
    }

    return join(config.dataPath, 'worlds', `${config.worldName}.wld`);
  }

  async writeConfig(): Promise<string> {
    const config = this.configService.getRuntimeConfig();
    const worldPath = this.resolveWorldPath(config);
    const worldDir = dirname(worldPath);
    await mkdir(worldDir, { recursive: true });

    const lines = [
      '# Generated by TerraPanel — do not edit while server is running',
      `world=${worldPath}`,
      `worldpath=${worldDir}`,
      `worldname=${config.worldName}`,
      `autocreate=${config.worldSize}`,
      `difficulty=${config.worldDifficulty}`,
      `port=${config.serverPort}`,
      `maxplayers=${config.maxPlayers}`,
      `motd=${config.motd}`,
      'secure=1',
    ];

    if (config.worldSeed) {
      lines.push(`seed=${config.worldSeed}`);
    }

    if (config.password) {
      lines.push(`password=${config.password}`);
    }

    const configPath = this.getConfigPath();
    await writeFile(configPath, `${lines.join('\n')}\n`, 'utf-8');
    return configPath;
  }
}
