import { Injectable } from '@nestjs/common';
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import type { InstanceConfig } from '../common/interfaces/instance-config.interface';
import { AppConfigService } from '../config/config.service';

@Injectable()
export class ServerConfigService {
  constructor(private readonly configService: AppConfigService) {}

  getInstanceConfigPath(instanceId: string): string {
    return join(
      this.configService.getDataPath(),
      'instances',
      instanceId,
      'serverconfig.txt',
    );
  }

  /** @deprecated 保留用于兼容旧测试，新代码请使用 writeInstanceConfig */
  getConfigPath(): string {
    return join(this.configService.getDataPath(), 'serverconfig.txt');
  }

  resolveWorldPathFromInstance(config: InstanceConfig): string {
    return config.worldPath;
  }

  async writeInstanceConfig(config: InstanceConfig): Promise<string> {
    const worldPath = config.worldPath;
    const worldDir = dirname(worldPath);
    await mkdir(worldDir, { recursive: true });

    const instanceDir = join(
      this.configService.getDataPath(),
      'instances',
      config.id,
    );
    await mkdir(instanceDir, { recursive: true });

    const lines = [
      '# Generated by TerraPanel — do not edit while server is running',
      `world=${worldPath}`,
      `worldpath=${worldDir}`,
      `worldname=${config.worldName}`,
      `autocreate=${config.worldSize}`,
      `difficulty=${config.worldDifficulty}`,
      `port=${config.port}`,
      `maxplayers=${config.maxPlayers}`,
      `motd=${config.motd}`,
      'secure=1',
    ];

    if (config.worldSeed) {
      lines.push(`seed=${config.worldSeed}`);
    }

    if (config.password) {
      lines.push(`password=${config.password}`);
    }

    const configPath = this.getInstanceConfigPath(config.id);
    await writeFile(configPath, `${lines.join('\n')}\n`, 'utf-8');
    return configPath;
  }

  /** @deprecated 保留用于兼容旧测试 */
  resolveWorldPath(config: {
    worldPath: string;
    worldName: string;
    dataPath: string;
  }): string {
    if (config.worldPath) {
      return config.worldPath;
    }

    return join(config.dataPath, 'worlds', `${config.worldName}.wld`);
  }

  /** @deprecated 保留用于兼容旧测试 */
  async writeConfig(): Promise<string> {
    const config = this.configService.getRuntimeConfig();
    const worldPath = this.resolveWorldPath(config);
    const worldDir = dirname(worldPath);
    await mkdir(worldDir, { recursive: true });

    const lines = [
      '# Generated by TerraPanel — do not edit while server is running',
      `world=${worldPath}`,
      `worldpath=${worldDir}`,
      `worldname=${config.worldName}`,
      `autocreate=${config.worldSize}`,
      `difficulty=${config.worldDifficulty}`,
      `port=${config.serverPort}`,
      `maxplayers=${config.maxPlayers}`,
      `motd=${config.motd}`,
      'secure=1',
    ];

    if (config.worldSeed) {
      lines.push(`seed=${config.worldSeed}`);
    }

    if (config.password) {
      lines.push(`password=${config.password}`);
    }

    const configPath = this.getConfigPath();
    await writeFile(configPath, `${lines.join('\n')}\n`, 'utf-8');
    return configPath;
  }
}
